### **Supervised Learning | Unsupervised Learning | Reinforcement Learning**
1. SL -> algorithm is trained on a labelled dataset i.e regression, classification
2. UL -> algorithm is given input data without explicit instructions on what to do with it i.e clustering
3. RL -> an agent learns to make decisions by the interacting with its environment

# **Class**

In [12]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 45)
print(p1.name)
print(p1.age)

John
45


In [20]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def printname(self):
    print(self.name)

pname = input("Enter name: ")
page = int(input("Enter age: "))

p1 = Person(pname, page)

p1.printname()

print(p1.name)
print(p1.age)

Enter name: Hamdan
Enter age: 20
Hamdan
Hamdan
20


In [16]:
class Manager(Person):
  def __init__(self, name, age, salary, project):
    self.salary = salary
    self.project = project
    super().__init__(name, age)

  def work(self):
    print(f"{self.name} is working on {self.project}")

  def show_salary(self):
    print(f"{self.name} salary is {self.salary}")

  def show_info(self):
    print(f"Name: {self.name}, Age: {self.age}, Salary: {self.salary}, Project: {self.project}")

m1 = Manager("John", 45, 10000, "Python")
m1.work()
m1.show_salary()
m1.show_info()

John is working on Python
John salary is 10000
Name: John, Age: 45, Salary: 10000, Project: Python


# **NumPy | Arrays and Vectorized Computation**

DL/ML/ANN -> Mathematical Formulae -> in NumPy
Data Cleaning

Data PreProcessing


In [1]:
import numpy as np

In [38]:
import pprint

In [27]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
new_row1 = np.concatenate([data[0], [10]])
new_row2 = np.concatenate([data[1], [20]])
new_data = np.vstack([new_row1, new_row2])
new_data

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [50]:
arr3d = np.array([
                  [[1,2], [3,4]],
                  [[5,6], [7,8]],
                  [[9,10], [11,12]]
                  ])
print(arr3d)
print(f"Shape : {arr3d.shape}")


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape : (3, 2, 2)


In [60]:
arr3db =[[[13, 14], [15, 16]]]
arr3d = np.append(arr3d, arr3db, axis=0)
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[13, 14],
        [15, 16]],

       [[13, 14],
        [15, 16]]])

In [61]:
arr3d = np.delete(arr3d, slice(3, 6), axis=0)

In [62]:
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [63]:
arr3d.shape

(3, 2, 2)

In [132]:
arr3d.ndim

3

In [6]:
arr1 = np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [94]:
np.arange(10,50,5) # step size (3rd arg)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [96]:
np.linspace(10, 50, 5) #no. of elements (3rd arg) (x, y, num = z)

array([10., 20., 30., 40., 50.])

In [40]:
arr2 = list(range(100))
pprint.pformat(arr2)

'[0,\n 1,\n 2,\n 3,\n 4,\n 5,\n 6,\n 7,\n 8,\n 9,\n 10,\n 11,\n 12,\n 13,\n 14,\n 15,\n 16,\n 17,\n 18,\n 19,\n 20,\n 21,\n 22,\n 23,\n 24,\n 25,\n 26,\n 27,\n 28,\n 29,\n 30,\n 31,\n 32,\n 33,\n 34,\n 35,\n 36,\n 37,\n 38,\n 39,\n 40,\n 41,\n 42,\n 43,\n 44,\n 45,\n 46,\n 47,\n 48,\n 49,\n 50,\n 51,\n 52,\n 53,\n 54,\n 55,\n 56,\n 57,\n 58,\n 59,\n 60,\n 61,\n 62,\n 63,\n 64,\n 65,\n 66,\n 67,\n 68,\n 69,\n 70,\n 71,\n 72,\n 73,\n 74,\n 75,\n 76,\n 77,\n 78,\n 79,\n 80,\n 81,\n 82,\n 83,\n 84,\n 85,\n 86,\n 87,\n 88,\n 89,\n 90,\n 91,\n 92,\n 93,\n 94,\n 95,\n 96,\n 97,\n 98,\n 99]'

In [9]:
%timeit arr3 = arr1 * 2
%timeit arr4 = [x * 2 for x in arr2]

1.36 µs ± 309 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
5.43 µs ± 304 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
data.shape

(2, 3)

In [32]:
data.dtype

dtype('int64')

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [69]:
np.full(5, 44)

array([44, 44, 44, 44, 44])

In [79]:
np.full((2, 3, 5), 44)

array([[[44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44]],

       [[44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44]]])

In [70]:
np.zeros_like(data)

array([[0, 0, 0],
       [0, 0, 0]])

In [72]:
np.random.random(4)

array([0.74558956, 0.99819593, 0.57712446, 0.70787449])

In [76]:
np.random.random((1, 3, 2))

array([[[0.76295644, 0.79924204],
        [0.96989486, 0.69705874],
        [0.43511514, 0.84831087]]])

In [86]:
rng = np.random.default_rng(seed=42)
rndm = rng.integers(low=5, high=10, size=(2, 3))
rndm

array([[5, 8, 8],
       [7, 7, 9]])

In [89]:
x = [i*5 for i in range(10)]
x

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

In [104]:
arra = np.array([1, 1, 1])
arrb = np.array([2, 2, 2])
arrc = np.array([3, 3, 3])
arrd = np.array([4, 4, 4])

arrVer = np.vstack([arra, arrb, arrc, arrd])
arrHor = np.hstack([arra, arrb, arrc, arrd])

print(f"Vertical Stacking(vstack):\n{arrVer} \nHorizontal Stacking(hstack): \n{arrHor}")

Vertical Stacking(vstack):
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]] 
Horizontal Stacking(hstack): 
[1 1 1 2 2 2 3 3 3 4 4 4]


In [105]:
arrVer[1]

array([2, 2, 2])

In [111]:
arrVer[2:]

array([[3, 3, 3],
       [4, 4, 4]])

In [122]:
arr10 = np.arange(10)
arr11 = np.linspace(-5, 15, 10)

print(arr10)
print(arr11)

[0 1 2 3 4 5 6 7 8 9]
[-5.         -2.77777778 -0.55555556  1.66666667  3.88888889  6.11111111
  8.33333333 10.55555556 12.77777778 15.        ]


In [123]:
arr10<arr11

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [129]:
arr20 = np.arange(1, 16)
arr20 = arr20.reshape(3, 5)
arr20

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [131]:
arr21 = arr20[:2, 1:3]
arr21

array([[2, 3],
       [7, 8]])

## Homework
1. add()
2. subtract()
3. multiply()
4. divide()
5. sqrt()
6. dot() / @
7. min()
8. max()
9. transpose()

In [137]:
arr30 = np.arange(5)
arr31 = np.arange(5, 10)

print(arr30)
print(arr31)

%timeit arr30 @ arr31
%timeit np.dot(arr30, arr31)

[0 1 2 3 4]
[5 6 7 8 9]
2.17 µs ± 350 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.23 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [144]:
arr32 = np.arange(10)
arr32 = arr32.reshape(5, 2)
print(f"Transpose: {arr32.T}")
pprint.pprint(f"Normal: {arr32}")

Transpose: [[0 2 4 6 8]
 [1 3 5 7 9]]
'Normal: [[0 1]\n [2 3]\n [4 5]\n [6 7]\n [8 9]]'


In [161]:
import csv

In [163]:
filepath = '/content/Iris.csv'

In [170]:
data = []

with open(filepath, 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  for row in reader:
    data.append(row)
  data = np.array(data)

data

array([['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
        'PetalWidthCm', 'Species'],
       ['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['16', '5.7', '4.4', '1.5', '0.4

In [171]:
np.save(open('data.npy', 'wb'), data)

In [157]:
import pandas as pd

In [160]:
ds =pd.read_csv("/content/Iris.csv")
ds.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# **Functions**

In [23]:
x = 10
y = 20

z = x + y
print(z)

30


In [24]:
def add(x, y):
  z = x + y
  return z

print(add(x, y))

30
